export const RESTURANT_DATA = {
  statusCode: 0,
  data: {
    cacheExpiryTime: 320,
    pages: 1,
    pageIndex: 0,
    scrubber: 0,
    filters: [
      {
        type: "FilterWidget",
        title: "Cuisines",
        key: "CUISINES",
        configType: "checkbox",
        visible: 1,
        options: [
          {
            option: "Afghani",
            selected: 0,
            visible: 1,
          },
          {
            option: "American",
            selected: 0,
            visible: 1,
          },
          {
            option: "Arabian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Asian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Bakery",
            selected: 0,
            visible: 1,
          },
          {
            option: "Beverages",
            selected: 0,
            visible: 1,
          },
          {
            option: "Biryani",
            selected: 0,
            visible: 1,
          },
          {
            option: "Burgers",
            selected: 0,
            visible: 1,
          },
          {
            option: "Cafe",
            selected: 0,
            visible: 1,
          },
          {
            option: "Chaat",
            selected: 0,
            visible: 1,
          },
          {
            option: "Chinese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Continental",
            selected: 0,
            visible: 1,
          },
          {
            option: "Desserts",
            selected: 0,
            visible: 1,
          },
          {
            option: "Fast Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Gujarati",
            selected: 0,
            visible: 1,
          },
          {
            option: "Hyderabadi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Ice Cream",
            selected: 0,
            visible: 1,
          },
          {
            option: "Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Italian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Italian-American",
            selected: 0,
            visible: 1,
          },
          {
            option: "Juices",
            selected: 0,
            visible: 1,
          },
          {
            option: "Kebabs",
            selected: 0,
            visible: 1,
          },
          {
            option: "Lebanese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mexican",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mughlai",
            selected: 0,
            visible: 1,
          },
          {
            option: "North Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pastas",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pizzas",
            selected: 0,
            visible: 1,
          },
          {
            option: "Rajasthani",
            selected: 0,
            visible: 1,
          },
          {
            option: "Salads",
            selected: 0,
            visible: 1,
          },
          {
            option: "Seafood",
            selected: 0,
            visible: 1,
          },
          {
            option: "Snacks",
            selected: 0,
            visible: 1,
          },
          {
            option: "South Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Special Discount from (The Scoop)",
            selected: 0,
            visible: 1,
          },
          {
            option: "Street Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Sweets",
            selected: 0,
            visible: 1,
          },
          {
            option: "Tandoor",
            selected: 0,
            visible: 1,
          },
          {
            option: "Thalis",
            selected: 0,
            visible: 1,
          },
          {
            option: "Waffle",
            selected: 0,
            visible: 1,
          },
        ],
        detail: "",
        heading: "Cuisines",
        applicable: 1,
        searchable: 1,
      },
      {
        type: "FilterWidget",
        title: "Show Restaurants With",
        key: "SHOW_RESTAURANTS_WITH",
        configType: "checkbox",
        visible: 1,
        options: [
          {
            option: "Pure Veg",
            selected: 0,
            visible: 1,
          },
        ],
        detail: "",
        heading: "Offers & More",
        applicable: 1,
        searchable: 0,
      },
    ],
    sorts: [
      {
        type: "SortWidget",
        key: "RELEVANCE",
        title: "Relevance",
        selected: 1,
        visible: 1,
        defaultSelection: true,
      },
      {
        type: "SortWidget",
        key: "DELIVERY_TIME",
        title: "Delivery Time",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "RATING",
        title: "Rating",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO",
        title: "Cost: Low to High",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO_H2L",
        title: "Cost: High to Low",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
    ],
    configs: {
      ribbons: {
        PREORDER: {
          type: "PREORDER",
          text: "Preorder",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 3,
        },
        EXCLUSIVE: {
          type: "EXCLUSIVE",
          text: "Exclusive",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 2,
        },
        NEW: {
          type: "NEW",
          text: "Newly Added",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 4,
        },
        REPEAT: {
          type: "REPEAT",
          text: "Repeat",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#D53D4C",
          bottomBackgroundColor: "#B02331",
          priority: 6,
        },
        CLOUD: {
          type: "CLOUD",
          text: "Daily Menus",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 5,
        },
        PREMIUM: {
          type: "PREMIUM",
          text: "Premium",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#8a584b",
          bottomBackgroundColor: "#583229",
          priority: 7,
        },
        PROMOTED: {
          type: "PROMOTED",
          text: "Promoted",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#3a3c41",
          bottomBackgroundColor: "#1e2023",
          priority: 1,
        },
      },
      croutons: {
        RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "${amount} extra levied on some restaurants",
        },
        SERVICEABLE_WITH_BANNER_RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "rain_crouton_4x",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Few restaurants unserviceable due to rains",
        },
      },
    },
    cards: [
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "topCarousel",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 635529,
                  creativeId: "rng/md/carousel/production/pneknawbadtvceqzwiep",
                  type: "restaurantCollectionV2",
                  link: "49301",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181635,
                  creativeId: "rng/md/carousel/production/yparhmxrby5lv0ubsel4",
                  type: "restaurantCollectionV2",
                  link: "56413",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607188,
                  creativeId: "rng/md/carousel/production/oxe97jexxbnxqtbhg2zo",
                  type: "restaurantCollectionV2",
                  link: "11740",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607195,
                  creativeId: "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
                  type: "restaurantCollectionV2",
                  link: "56421",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "openFilter",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181684,
                  creativeId: "bkhjfipzydkoqncrxpyi",
                  type: "restaurantCollectionV2",
                  link: "11718",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Offers Near You",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Offers Near You",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "eyperwsfhaoa5vktjtu4",
                  dwebOpenFilterDeselectIcon: "urw8usdf4mk9aywd59gq",
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181680,
                  creativeId: "a3jqjjod5taken7dh1bs",
                  type: "restaurantCollectionV2",
                  link: "11721",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Veg Only",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Vegetarian Options",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "qtjc8dzfexg72lug37a0",
                  dwebOpenFilterDeselectIcon: "bm8bziikwyvwqsml1clm",
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "seeAllRestaurants",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "seeAllRestaurants",
          data: {
            title: "SEE ALL",
            totalOpenRestaurants: 271,
            cards: [
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "424863",
                  name: "Rolls Mania",
                  uuid: "c4229029-9f27-4a02-ac22-77f980981572",
                  city: "115",
                  area: "Civil Lines",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "w4tqxthgs4sebffdulei",
                  cuisines: [
                    "Fast Food",
                    "Beverages",
                    "Snacks",
                    "North Indian",
                  ],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 26,
                  minDeliveryTime: 26,
                  maxDeliveryTime: 26,
                  slaString: "26 MINS",
                  lastMileTravel: 3,
                  slugs: {
                    restaurant: "rolls-mania-civil-lines-civil-lines-2",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "957, Ground Floor, Near Allahabad Bank Chauraha - Jhansi Road, Civil Lines, Jhansi, Uttar Pradesh - 957, Ground Floor, Sadar Bazar - Jhansi Road, Civil Lines, Jhansi, Uttar Pradesh - 284001",
                  locality: "Allahabad Bank Chauraha",
                  parentId: 171118,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7014061~p=1~eid=00000188-95e1-76c5-05d2-447c00a00136",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "3 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "40% OFF",
                    subHeader: "UPTO ₹80",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "424863",
                    deliveryTime: 26,
                    minDeliveryTime: 26,
                    maxDeliveryTime: 26,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.2",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "702179",
                  name: "Avadh Foods",
                  uuid: "1c861be4-2a8a-40ea-8940-bbf3fdaf313e",
                  city: "115",
                  area: "Civil Lines",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "19b555f364f7c5e0db9e815efb078b35",
                  cuisines: ["Indian", "Snacks", "Biryani"],
                  tags: [],
                  costForTwo: 10000,
                  costForTwoString: "₹100 FOR TWO",
                  deliveryTime: 20,
                  minDeliveryTime: 20,
                  maxDeliveryTime: 20,
                  slaString: "20 MINS",
                  lastMileTravel: 1.600000023841858,
                  slugs: {
                    restaurant: "avadh-food-civil-lines-civil-lines",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "Near D.A.V SCHOOL, PATHORIYA, OUTSIDE DATIYA GATE SECOND, ZONE 2, JHANSI",
                  locality: "D.a.v school",
                  parentId: 37907,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "702179",
                    deliveryTime: 20,
                    minDeliveryTime: 20,
                    maxDeliveryTime: 20,
                    lastMileTravel: 1.600000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.1",
                  totalRatings: 100,
                  new: true,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "623940",
                  name: "Burger Singh (Big Punjabi Burgers)",
                  uuid: "34ca5e0f-9018-4757-943a-daeca82cb3f4",
                  city: "115",
                  area: "Civil Lines",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "gd57zvqxavl133kqx4kq",
                  cuisines: [
                    "Burgers",
                    "Snacks",
                    "Desserts",
                    "Beverages",
                    "Fast Food",
                    "American",
                    "Indian",
                    "Biryani",
                  ],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 17,
                  minDeliveryTime: 17,
                  maxDeliveryTime: 17,
                  slaString: "17 MINS",
                  lastMileTravel: 1.7000000476837158,
                  slugs: {
                    restaurant:
                      "burger-singh-(big-punjabi-burgers)-civil-lines-civil-lines-3",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "372/13, Civil Lines, Near Babu Lal Karkhana, Gwalior Road, Jhansi, ZONE 3, Jhansi, Uttar Pradesh 284001",
                  locality: "Gwalior Road",
                  parentId: 375065,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.7 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "623940",
                    deliveryTime: 17,
                    minDeliveryTime: 17,
                    maxDeliveryTime: 17,
                    lastMileTravel: 1.7000000476837158,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.1",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "284767",
                  name: "Pizza Factory & Food",
                  uuid: "af839c9c-16f8-4499-bb3d-9caeb3bf9c02",
                  city: "115",
                  area: "Jhokan Bagh",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "gpn95ucbzlr4clfq89gc",
                  cuisines: ["Chinese", "Italian-American", "Pizzas"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 32,
                  minDeliveryTime: 32,
                  maxDeliveryTime: 32,
                  slaString: "32 MINS",
                  lastMileTravel: 4.300000190734863,
                  slugs: {
                    restaurant: "pizza-factory-civil-lines-civil-lines-2",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address: "434, KHUSIPURA JHANSI",
                  locality: "Khushipura",
                  parentId: 158556,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7014048~p=4~eid=00000188-95e1-76c5-05d2-447d00a00446",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.3 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹120 OFF",
                    subHeader: "ABOVE ₹199",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "284767",
                    deliveryTime: 32,
                    minDeliveryTime: 32,
                    maxDeliveryTime: 32,
                    lastMileTravel: 4.300000190734863,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "3.5",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "428827",
                  name: "MAKE MY PIZZA",
                  uuid: "8809a4bd-b2c4-424d-a247-b355b8c18c30",
                  city: "115",
                  area: "Indrapuri",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "pb2rgodyy9xzmhrlmwni",
                  cuisines: ["Pizzas", "Indian"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 18,
                  minDeliveryTime: 18,
                  maxDeliveryTime: 18,
                  slaString: "18 MINS",
                  lastMileTravel: 0.5,
                  slugs: {
                    restaurant: "make-my-pizza-civil-lines-civil-lines-2",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "Abhishek Gupta, Near White House,  Mission Compound , Jhansi, C.P. MISSION  COMPOUND, ZONE 3, Jhansi, Uttar  Pradesh - 284003",
                  locality: "Mission Compound",
                  parentId: 130542,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.5 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "50% OFF",
                    subHeader: "UPTO ₹100",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "428827",
                    deliveryTime: 18,
                    minDeliveryTime: 18,
                    maxDeliveryTime: 18,
                    lastMileTravel: 0.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "98032",
                  name: "Pizza Hut",
                  uuid: "f3066ee2-c526-40d7-9008-ff64d4b17e10",
                  city: "115",
                  area: "Civil Lines",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
                  cuisines: ["Pizzas"],
                  tags: [],
                  costForTwo: 35000,
                  costForTwoString: "₹350 FOR TWO",
                  deliveryTime: 26,
                  minDeliveryTime: 26,
                  maxDeliveryTime: 26,
                  slaString: "26 MINS",
                  lastMileTravel: 2.5999999046325684,
                  slugs: {
                    restaurant: "pizza-hut-civil-lanes-test-jhansi",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "Om complex 943 Civil lines shivpuri Road Jhansi UP-284001",
                  locality: "Shivpuri Road",
                  parentId: 721,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2.5 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹399",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "98032",
                    deliveryTime: 26,
                    minDeliveryTime: 26,
                    maxDeliveryTime: 26,
                    lastMileTravel: 2.5999999046325684,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.6",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "104802",
                  name: "7th Heaven",
                  uuid: "d6af0210-6d6e-400b-9e3a-ddd08bc4d643",
                  city: "115",
                  area: "Civil Lines",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "bl485e11nxveq2otg9i4",
                  cuisines: ["Bakery"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 22,
                  minDeliveryTime: 22,
                  maxDeliveryTime: 22,
                  slaString: "22 MINS",
                  lastMileTravel: 2.5999999046325684,
                  slugs: {
                    restaurant: "7th-heaven-civil-lines-civil-lines",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "1081, Opposite Promod, Pertrol Pump, Semi Basement, Civil Lines, Jhansi",
                  locality: "Shivpuri - Jhansi Rd",
                  parentId: 19,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7014111~p=10~eid=00000188-95e1-76c5-05d2-447f00a00a00",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2.5 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "60% OFF",
                    subHeader: "UPTO ₹120",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "104802",
                    deliveryTime: 22,
                    minDeliveryTime: 22,
                    maxDeliveryTime: 22,
                    lastMileTravel: 2.5999999046325684,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "3.9",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "105051",
                  name: "Burger Ji",
                  uuid: "d12f783a-66c7-4d86-a09e-5e4f23c27607",
                  city: "115",
                  area: "Civil Lines",
                  totalRatingsString: "5000+ ratings",
                  cloudinaryImageId: "h14erb1udxpttvg6n5uy",
                  cuisines: ["Italian", "Continental", "Snacks"],
                  tags: [],
                  costForTwo: 25000,
                  costForTwoString: "₹250 FOR TWO",
                  deliveryTime: 25,
                  minDeliveryTime: 25,
                  maxDeliveryTime: 25,
                  slaString: "25 MINS",
                  lastMileTravel: 3,
                  slugs: {
                    restaurant: "burger-point-civil-lines-civil-lines",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address: "222, GF Civil Lines, Jhansi",
                  locality: "",
                  parentId: 51346,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "3 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "50% OFF",
                    subHeader: "UPTO ₹100",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "105051",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.1",
                  totalRatings: 5000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "670276",
                  name: "Chai Shai Bar",
                  uuid: "ca560b31-75ec-49dc-9b0c-74b66136914f",
                  city: "115",
                  area: "Sipri Bazar",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "097af09461fcb30498221a4aa75207e8",
                  cuisines: ["Beverages", "Fast Food", "Snacks", "Burgers"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 21,
                  minDeliveryTime: 21,
                  maxDeliveryTime: 21,
                  slaString: "21 MINS",
                  lastMileTravel: 0.8999999761581421,
                  slugs: {
                    restaurant: "chai-shai-bar-civil-lines-civil-lines-2",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "500, Mission Compound, Jhansi, Uttar Pradesh 284002, India",
                  locality: "Mission Compound",
                  parentId: 57137,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.8 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "670276",
                    deliveryTime: 21,
                    minDeliveryTime: 21,
                    maxDeliveryTime: 21,
                    lastMileTravel: 0.8999999761581421,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "702180",
                  name: "Nandi Butter Counter",
                  uuid: "a78c4067-0399-465a-bfb9-c08677f34b88",
                  city: "115",
                  area: "Panchtantra Park",
                  totalRatingsString: "20+ ratings",
                  cloudinaryImageId: "f1bc9ddf53de574cdc35ab2f717df234",
                  cuisines: ["South Indian"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 20,
                  minDeliveryTime: 20,
                  maxDeliveryTime: 20,
                  slaString: "20 MINS",
                  lastMileTravel: 1.899999976158142,
                  slugs: {
                    restaurant: "nandi-butter-counter-civil-lines-civil-lines",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address: "INFRONT OF DHYANCHANDRA STADIUM, ZONE 4, JHANSI",
                  locality: "Dhyanchandra stadium",
                  parentId: 419459,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.8 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "702180",
                    deliveryTime: 20,
                    minDeliveryTime: 20,
                    maxDeliveryTime: 20,
                    lastMileTravel: 1.899999976158142,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.1",
                  totalRatings: 20,
                  new: true,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "639339",
                  name: "KFC",
                  uuid: "a777c5cb-1a15-47f9-a9b5-43728928ece5",
                  city: "115",
                  area: "Jhokan Bagh",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
                  cuisines: [
                    "Burgers",
                    "Biryani",
                    "American",
                    "Snacks",
                    "Fast Food",
                  ],
                  tags: [],
                  costForTwo: 40000,
                  costForTwoString: "₹400 FOR TWO",
                  deliveryTime: 23,
                  minDeliveryTime: 23,
                  maxDeliveryTime: 23,
                  slaString: "23 MINS",
                  lastMileTravel: 2.0999999046325684,
                  slugs: {
                    restaurant: "kfc-athena-hub-civil-lines",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "KFC Restaurant G-2, Ground floor, Athena Hub, 362- Civil lines Jhansi - Uttar Pradesh -284001.",
                  locality: "Jeevan Shah",
                  parentId: 547,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "20% OFF",
                    subHeader: "UPTO ₹50",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "639339",
                    deliveryTime: 23,
                    minDeliveryTime: 23,
                    maxDeliveryTime: 23,
                    lastMileTravel: 2.0999999046325684,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.7",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "206120",
                  name: "7th Heaven cafe",
                  uuid: "2ad6fff6-67c9-44da-90c1-260b8b24c1a9",
                  city: "115",
                  area: "Cantt",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "xtkexbsuypj4jn1fttcr",
                  cuisines: ["Bakery", "Ice Cream", "Pizzas"],
                  tags: [],
                  costForTwo: 25000,
                  costForTwoString: "₹250 FOR TWO",
                  deliveryTime: 25,
                  minDeliveryTime: 25,
                  maxDeliveryTime: 25,
                  slaString: "25 MINS",
                  lastMileTravel: 4.699999809265137,
                  slugs: {
                    restaurant: "7th-heaven-sadar-bazar-sadar-bazar",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "11/32 pannalal compound,near vandana dresses Sadar Bazar, Cantt, Jhansi, Uttar Pradesh 284001, India",
                  locality: "Sadar Bazar",
                  parentId: 24161,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7014053~p=13~eid=00000188-95e1-76c5-05d2-448000a00d1f",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.6 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "20% OFF",
                    subHeader: "UPTO ₹50",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "206120",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    lastMileTravel: 4.699999809265137,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "3.8",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "490849",
                  name: "NIC Ice Creams",
                  uuid: "bc1a094c-e7a5-4e31-90f1-a669701ca890",
                  city: "115",
                  area: "Shakti Nagar Colony",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "d461cb7eac503656a2b4bb13e7c60b97",
                  cuisines: ["Ice Cream", "Desserts"],
                  tags: [],
                  costForTwo: 12000,
                  costForTwoString: "₹120 FOR TWO",
                  deliveryTime: 16,
                  minDeliveryTime: 16,
                  maxDeliveryTime: 16,
                  slaString: "16 MINS",
                  lastMileTravel: 2,
                  slugs: {
                    restaurant:
                      "nic-natural-ice-creams-jeevan-shah-civil-lines",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "Shop No 968/1, Aabha Complex,Jeevan Shah, Shakti Nagar Colony, Loha Mandi, Jhansi, Uttar Pradesh 284002",
                  locality: "Jeevan Shah",
                  parentId: 6249,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "EVERY ITEM",
                    subHeader: "@ ₹159",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "490849",
                    deliveryTime: 16,
                    minDeliveryTime: 16,
                    maxDeliveryTime: 16,
                    lastMileTravel: 2,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.5",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "106205",
                  name: "Singh Foods- By Hotel Singh Regency",
                  uuid: "a5703576-833e-419f-afe8-3e223dffcc07",
                  city: "115",
                  area: "Sipri Bazar",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "k5ael9mtlc8yxfcui8qu",
                  cuisines: ["North Indian", "Chinese"],
                  tags: [],
                  costForTwo: 40000,
                  costForTwoString: "₹400 FOR TWO",
                  deliveryTime: 20,
                  minDeliveryTime: 20,
                  maxDeliveryTime: 20,
                  slaString: "20 MINS",
                  lastMileTravel: 1.399999976158142,
                  slugs: {
                    restaurant:
                      "singh-foods-singh-regency-civil-lines-civil-lines",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address:
                    "Gondu Compound Churaha, Satish Nagar, Sipri, Jhansi, Uttar Pradesh 284003",
                  locality: "Satish Nagar",
                  parentId: 188439,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.3 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "40% OFF",
                    subHeader: "UPTO ₹80",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "106205",
                    deliveryTime: 20,
                    minDeliveryTime: 20,
                    maxDeliveryTime: 20,
                    lastMileTravel: 1.399999976158142,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.9",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "279467",
                  name: "Janta Thali",
                  uuid: "f590d008-bfec-47a7-bfd3-834d16662df0",
                  city: "115",
                  area: "Civil Lines",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "hmbkxaasvko5injc9ock",
                  cuisines: ["North Indian"],
                  tags: [],
                  costForTwo: 25000,
                  costForTwoString: "₹250 FOR TWO",
                  deliveryTime: 23,
                  minDeliveryTime: 23,
                  maxDeliveryTime: 23,
                  slaString: "23 MINS",
                  lastMileTravel: 2.0999999046325684,
                  slugs: {
                    restaurant: "janta-thali-civil-lines-civil-lines-2",
                    city: "jhansi",
                  },
                  cityState: "115",
                  address: "Shop No - 1, Jeevan Shah Tirha, Jhansi",
                  locality: "Nehru Marg",
                  parentId: 109721,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 1900,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 1900,
                    message: "",
                    title: "Delivery Charge",
                    amount: "1900",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹100 OFF",
                    subHeader: "ABOVE ₹199",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "279467",
                    deliveryTime: 23,
                    minDeliveryTime: 23,
                    maxDeliveryTime: 23,
                    lastMileTravel: 2.0999999046325684,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.2",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
            ],
            totalRestaurants: 271,
          },
          subtype: "personalized",
        },
        parentWidget: false,
      },
    ],
    nextPageFetch: 0,
  },
  tid: "7fa5a023-775f-42e4-9c68-747abff8e133",
  sid: "7hu29b69-eb02-44fc-9586-c6b6189b0b9c",
  deviceId: "35cf1caa-9e46-85de-897e-87285ca100e4",
  csrfToken: "iBPdAvzgyQNF-o4hcoEAdZeAuVUb-HtG0bnfwB8I",
};
